/*---------------------------------------------------------------------------*
 *  cli101d.d - LIBERO dialog data definitions for cli101.c.                 *
 *  Generated by LIBERO 2.10 on  7 Dec, 1995, 15:12.                         *
 *  Schema file used: lrschema.c.                                            *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
#define terminate_event                 -1
#define disconnect_event                0
#define error_event                     1
#define from_parent_event               2
#define ok_event                        3
#define parent_error_event              4
#define soft_error_event                5
#define time_to_logon_event             6
#define timeout_event                   7
#define _LR_STATE_after_init            0
#define _LR_STATE_have_input            1
#define _LR_STATE_parent_message        2
#define _LR_STATE_defaults              3
#define _LR_defaults_state              3

/*- Variables used by dialog interpreter ------------------------------------*/

typedef int t_event;                    /*  Type for dialog entity           */
static t_event
    _LR_event,                          /*  Event for state transition       */
    _LR_state,                          /*  Current dialog state             */
    _LR_savest,                         /*  Saved dialog state               */
    _LR_index,                          /*  Index into vector table          */
    the_next_event,                     /*  Next event from module           */
    the_exception_event;                /*  Exception event from module      */

static word
   *_LR_vecptr;                         /*  Pointer into vector table        */

static Bool
    exception_raised;                   /*  TRUE if exception raised         */

/*- Function prototypes -----------------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

local  raise_exception                  (t_event event);
MODULE initialise_the_program           (void);
MODULE get_external_event               (void);
MODULE check_if_time_to_logon_parent    (void);
MODULE clear_parent_connect_timeout     (void);
MODULE connect_to_parent_host           (void);
MODULE decode_message_from_parent       (void);
MODULE disconnect_from_parent_host      (void);
MODULE display_message                  (void);
MODULE set_parent_connect_timeout       (void);
MODULE signal_fatal_error_abort         (void);
MODULE terminate_the_program            (void);
MODULE wait_for_parent_message          (void);

/*- Static areas ------------------------------------------------------------*/

static word _LR_nextst [][8] =
{
    { 0,0,0,1,0,0,0,0 },
    { 0,0,2,0,0,0,1,1 },
    { 1,0,0,1,0,0,0,0 },
    { 0,3,0,0,1,1,0,0 }
};

static word _LR_action [][8] =
{
    { 0,2,0,1,0,0,0,0 },
    { 0,0,3,0,0,0,5,4 },
    { 7,0,0,6,0,0,0,0 },
    { 0,9,0,0,7,8,0,0 }
};

static word _LR_vector [][3+1] =
{
    {0},
    {2,1,9,_LR_STOP},
    {8,_LR_STOP},
    {3,_LR_STOP},
    {0,9,_LR_STOP},
    {2,9,_LR_STOP},
    {5,9,_LR_STOP},
    {4,6,9,_LR_STOP},
    {9,_LR_STOP},
    {4,7,8,_LR_STOP}
};

static function _LR_module [] =
{
    check_if_time_to_logon_parent,
    clear_parent_connect_timeout,
    connect_to_parent_host,
    decode_message_from_parent,
    disconnect_from_parent_host,
    display_message,
    set_parent_connect_timeout,
    signal_fatal_error_abort,
    terminate_the_program,
    wait_for_parent_message
};

